name = "YLEFlow"
uuid = "d394820d-ef7b-4333-a259-f3b9076cbdf1"
authors = ["vskokov <vladi@skokov.net> and contributors"]
version = "0.1.0"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Symbolics = "4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
